# Generated by Django 4.2.3 on 2023-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('json_items', models.CharField(max_length=1122)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=334)),
                ('phone', models.CharField(max_length=12)),
                ('state', models.CharField(max_length=53)),
                ('city', models.CharField(max_length=34)),
                ('zip_code', models.CharField(max_length=12)),
            ],
        ),
    ]
