# Generated by Django 4.2.3 on 2023-09-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='json_items',
        ),
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.CharField(default=' ', max_length=5000),
            preserve_default=False,
        ),
    ]
